// AuthStack Screens
export {default as Splash} from './Splash/Splash'
export {default as Onboarding} from './Onboarding/Onboarding'
export {default as AccountScreen} from './AccountScreen/AccountScreen'
export {default as NewPassword} from './NewPassword/index'
export {default as ForgetPassword} from './ForgetPassword/index' 
export {default as OTPVerification} from  './OTPVerification/index'
export {default as Interest} from './Interest/index'
export {default as EditProfile} from './EditProfile/index'
export {default as NotificationSetting} from './NotificationSetting/index'
export {default as PrivacyPolicy} from './PrivacyPolicy/index'
export {default as TermsOfUse} from './TermsofUse/index'
export {default as Notification} from './Notification/index'
export {default as DebateThis} from './DebuteThis/index'
export {default as InviteDebater} from './InviteDebater/index'
export {default as StartDebate} from './StartDebate/index'
export {default as Follower} from './Profile/Follower'
export {default as Following} from './Profile/Following'
export {default as Debates} from './Profile/Debates'
export {default as ChangePassword} from './ChangePassword/index'
export {default as OTPVerification2} from './OTPVerification2/index'
export {default as NewPassword2} from './NewPassword2/index'
export {default as ForgetPassword2} from './ForgetPassword2/index'
export {default as OTPVerification3} from './OTPVerification3/index'
export {default as NewPassword3} from './NewPassword3/index'
export {default as PasswordRecovered3} from './PasswordRecovered3/index'
 

// MainStack Screen 
export {default as Home} from './Home/index'
export {default as Headline} from './Headline/index'
export {default as AddLiveScreen} from './AddLiveStream/index'
export {default as Library} from './Library/index'
export {default as Profile} from './Profile/index'
